### ISSUE TITLE
Add `--x64` command line flag

### ISSUE THREAD

**Issue by avanhatt** [wellesley-prog-sys/wasmtime#11]
Analogous to `--aarch64`, we should have a command-line flag to run named rules with the x86-64 prelude files. The files you'll need to add can be found by looking at the `test_x64_rule_with_lhs_termname` and related test cases. 

The goal is to be able to run commands like this:

```
cargo run -- --x64 --term iadd --names iadd_base_case_32_or_64_lea --widths I64
```

Which currently fails with:
```
error: Found argument '--x64' which wasn't expected, or isn't valid in this context
```

**Comment by mmcloughlin** [comment]
I have this working in my rule chaining branch, not just for `--x86` but any of the ISLE compilations. The list of ISLE files is determined here dependent on `--name` option that can be `aarch64`, `x64`, ...:

https://github.com/avanhatt/wasmtime/blob/5420c0c14a570ae7fbcf62f71e84859081253bd4/cranelift/isle/veri/src/bin/expand.rs#L50-L67

As part of this, generated ISLE files are also produced on the fly.

Example of calling this tool with different `--name` arguments:
https://github.com/avanhatt/wasmtime/blob/5420c0c14a570ae7fbcf62f71e84859081253bd4/cranelift/isle/veri/output/expand.sh

This depends on the changes to `cranelift/codegen/meta` that landed upstream:

https://github.com/bytecodealliance/wasmtime/pull/8423
https://github.com/bytecodealliance/wasmtime/pull/8462

I have further extended this in my branch to assign a name to each ISLE compilation, for example:

https://github.com/avanhatt/wasmtime/blob/5420c0c14a570ae7fbcf62f71e84859081253bd4/cranelift/codegen/meta/src/isle.rs#L102
